# name: Automerge succesful dependabot pull requests

# #############################
# # Start the job on all push #
# #############################
# on: check_suite

# ###############
# # Set the Job #
# ###############
# jobs:
#   build:
#     # Name the Job
#     name: Automerge pull request
#     # Set the agent to run on
#     runs-on: ubuntu-latest
#     steps:
#       ################################
#       # Use action to merge automatically #
#       ################################
#       - name: Automerge pr
#         uses: shoogland/automerge-action@master
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
