---
name: Upload Website

on:
  push:
    branches:
      - main

concurrency: production_environment

jobs:
  deploy:
    if: github.repository == 'shoogland/shoogland-com'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v7

      - name: Setup Node.js (.nvmrc)
        uses: actions/setup-node@v7.0.0
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      # run the ci equivalent of npm install
      - name: npm ci
        run: |
          npm ci --only=production
          npm run dist

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4.3.0

      - name: Log in to ghcr.io
        uses: docker/login-action@v4.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push docker image
        uses: docker/build-push-action@v7.3.0
        with:
          context: .
          push: true
          tags: |
            ghcr.io/shoogland/shoogland-com:latest
            ghcr.io/shoogland/shoogland-com:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: get kubectl creds
        run: |
          doctl kubernetes cluster kubeconfig save \
            --expiry-seconds 600 sh-cluster-01

      - name: get shoost deployment
        run: |
          kubectl get deployment -n argocd www-shoogland \
            -o yaml > deployment.yaml

      - name: update image tag
        run: |
          IMAGE="ghcr.io/shoogland/shoogland-com"
          sed "s|${IMAGE}:.*|${IMAGE}:${GITHUB_SHA}|" \
            < deployment.yaml > deployment2.yaml

      - name: apply updated image
        run: kubectl apply -f deployment2.yaml
