name: Upload Website

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: 'eu-west-2'

    steps:
    - uses: actions/checkout@main

    # get the node version from the .nvmrc file
    - name: Read .nvmrc
      run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
      id: nvm

    # setup node based on the version from the .nvmrc file, fetched in the previous step
    - name: Setup Node.js (.nvmrc)
      uses: actions/setup-node@v1
      with:
        node-version: "${{ steps.nvm.outputs.NVMRC }}"

    # setup the node cache (node_modules) with github actions cache
    - name: Cache Node - npm
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-cache-

    # run the ci equivalent of npm install
    - name: npm ci
      run: |
        npm ci
        npm run dist

    - name: Push to GitHub Packages
      uses: docker/build-push-action@v1
      with:
        username: shoogland
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: shoogland/shoogland-com/my-blog
        tag_with_ref: true

    # - name: deploy
    #   run: aws s3 sync docs/.vuepress/dist s3://${{ secrets.AWS_S3_BUCKET }}/ --exclude "_redirects" --no-progress --delete

#     - name: change meta data (headers/cacheability)
#       run: aws s3 cp s3://${{ secrets.AWS_S3_BUCKET }}/ s3://${{ secrets.AWS_S3_BUCKET }}/ --exclude "index.html" --exclude "404.html" --recursive --metadata-directive REPLACE --expires 2022-01-01T00:00:00Z --cache-control max-age=604.800,public
