---
name: Renovate
on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  renovate:
    uses: shoogland/.github/.github/workflows/renovate.yml@main
    secrets: inherit
    permissions:
      contents: write
      pull-requests: write
      statuses: write
      issues: write
      checks: write
      vulnerability-alerts: read
